apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-max
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-max
  template:
    metadata:
      labels:
        app: hello-max
    spec:
      containers:
        - name: hello-max
          image: edbafjdu/hello_max
          ports:
            - name: http-port
              containerPort: 8080
