apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algo_training
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarlDue/argo-test
    targetRevision: HEAD
    path: kubernetes/algo_training
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: algo_training
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
