apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarlDue/argo-test
    targetRevision: HEAD
    path: kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-server
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-max
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarlDue/argo-test
    targetRevision: HEAD
    path: kubernetes/deployment-2.yaml  # Update the path to the deployment-2.yaml file
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-server  # Assuming you want to deploy it in the same namespace as echo-server
  syncPolicy:
    automated:
      prune: false
      selfHeal: false