apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello_max
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarlDue/argo-test
    targetRevision: HEAD
    path: kubernetes/hello_max
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hello_max
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
